language: java
matrix:
  include:
    # Headed Linux
    - os: linux
      jdk: oraclejdk11
    # Headless Linux
    - os: linux
      jdk: oraclejdk11
      env:
        - _JAVA_OPTIONS="-Djava.awt.headless=true -Dtestfx.robot=glass -Dtestfx.headless=true -Dprism.order=sw -Dprism.text=t2k -Dtestfx.setup.timeout=2500"
    # Headless macOS
    - os: osx
      osx_image: xcode10.1
      env:
        - _JAVA_OPTIONS="-Djava.awt.headless=true -Dtestfx.robot=glass -Dtestfx.headless=true -Dprism.order=sw -Dprism.text=t2k -Dtestfx.setup.timeout=2500"
    # Headed macOS is not currently possible on Travis.

before_install:
  - if [[ "${TRAVIS_OS_NAME}" == linux ]]; then export DISPLAY=:99.0; sh -e /etc/init.d/xvfb start; fi

install: true

before_script:
  - if [[ "${TRAVIS_OS_NAME}" == osx ]]; then brew update; brew cask reinstall caskroom/versions/java8; fi

script: >-
    ./config/travis/run-checks.sh &&
    ./gradlew clean checkstyleMain checkstyleTest test coverage coveralls asciidoctor

deploy:
  skip_cleanup: true
  provider: script
  script: ./config/travis/deploy_github_pages.sh
  on:
    branch: master

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
  - rm -f  $HOME/.gradle/caches/*/fileHashes/fileHashes.bin
  - rm -f  $HOME/.gradle/caches/*/fileHashes/fileHashes.lock

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
